### ISSUE TITLE
Location of examples and content of algorithms.jl

### ISSUE THREAD

**Issue by FrederikSchnack** [gaioguys/GAIO.jl#11]
Currently, the examples in `GAIO.jl/examples` and their dependencies get included in the GAIO package. This should be discussed. Possible options are for example: 
- Moving the examples to their own package.
- Keeping them at their place and remove the inclusion. 
- Moving them to `GAIO.jl/src/examples` and keep the inclusion.

Furthermore, we wanted to discuss the content of `GAIO.jl/src/algorithms.jl`, i.e. should we keep functions like the `adaptive_newton_step` in there? 

What are your opinions?

**Comment by cafaxo** [comment]
Instructions for testing examples in #16.

**Comment by cafaxo** [comment]
We can close this issue since #16 fixed one part and the other part is discussed in #12.
