### ISSUE TITLE
docs / github pages

### ISSUE THREAD

**Issue by gaioguy** [gaioguys/GAIO.jl#19]
I enabled github pages - but I am not sure what is required next.  Maybe we now need the CI integration?

**Comment by cafaxo** [comment]
On which branch did you enable it? (https://github.com/gaioguys/GAIO.jl/commit/080f66a5a978eb8521b3122a99e6aba4eacdd484#commitcomment-40557219)

**Comment by gaioguy** [comment]
On "master branch /docs folder"

**Comment by cafaxo** [comment]
I disabled it for now. The way this will work is that Documenter.jl creates a distached branch "gh-pages". We will then enable the Github pages feature for the **gh-pages** pages branch instead of master.

**Comment by cafaxo** [comment]
I manually pushed empty docs to https://gaioguys.github.io/GAIO.jl/

**Comment by gaioguy** [comment]
Ok, great.
